#!/bin/bash

docker stop prometheus
docker rm prometheus

docker run -it --rm \
 -p 9090:9090 \
 --name=prometheus \
 -v ${PWD}/configs/:/etc/prometheus/ \
 -v /mnt/synology/prometheus:/prometheus \
 prom/prometheus \
 --storage.tsdb.path /prometheus \
 --config.file /etc/prometheus/prometheus.yml \
 --storage.tsdb.retention.time 90d \
 --log.level=debug