#!/bin/bash

docker stop alertmanager
docker rm alertmanager

docker run -d --restart always \
 -p 9093:9093 \
 --name=alertmanager \
 -v ${PWD}/configs/alertmanager.yml:/alertmanager.yml \
 prom/alertmanager \
 --config.file /alertmanager.yml