global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: kb
    from: kbg
    smarthost: smtp.gmail.com:587
    auth_username: kbg
    auth_identity: kbg
    auth_password: <secret>
    send_resolved: true